const DEFAULT_SCRIPT_URL =
  "https://script.google.com/macros/s/AKfycbytHuWxCiTwSTM-1gbpt2UgWzGXWDhZD-QqllAyC6Tcy_xxrdD--Kk2QBjYGcXbubfY/exec";
const UPSTREAM_TIMEOUT_MS = Number(process.env.GOOGLE_SCRIPT_TIMEOUT_MS || 30000);
const UPSTREAM_RETRY_COUNT = Number(process.env.GOOGLE_SCRIPT_RETRY_COUNT || 1);
const db = require("../config/db");
const { sendAssessmentResultEmail, sendAdminNotificationEmail } = require("../utils/mailer");
const { computeTab3Scoring } = require("../utils/scoring");
const {
  getById,
  getActiveById,
  getByEmail,
  formatFullName,
} = require("../repositories/respondentRepository");
const { toDecryptedRespondent } = require("../utils/dataSecurity");

const ASSESSMENT_TYPE = "leadership_reset";

const ROW_TO_QKEY = {
  6: "q1",
  7: "q2",
  8: "q3",
  9: "q4",
  12: "q5",
  13: "q6",
  14: "q7",
  15: "q8",
  18: "q9",
  19: "q10",
  20: "q11",
  21: "q12",
};

const QUESTION_ROWS = [6, 7, 8, 9, 12, 13, 14, 15, 18, 19, 20, 21];

function buildScriptPayload(input, canonicalRespondent) {
  const firstName = canonicalRespondent?.firstname || input.firstName || "";
  const lastName = canonicalRespondent?.lastname || input.lastName || "";
  const respondentName = formatFullName(firstName, lastName) || input.respondent || "";
  const email = canonicalRespondent?.email || input.email || "";
  const respondentId = Number(canonicalRespondent?.id || input.respondentId || 0);

  const payload = {
    respondent: respondentName,
    firstName: String(firstName).trim(),
    lastName: String(lastName).trim(),
    email: String(email).trim(),
    respondentId,
    submittedAt: input.submittedAt || new Date().toISOString(),
    mode: "template-update",
    totalScore: Number(input.totalScore || 0),
    totalWeightedScore: Number(input.totalWeightedScore || 0),
    answersByRow: { ...(input.answersByRow || {}) },
    answersByQuestion: {},
    questionResponses: Array.isArray(input.questionResponses) ? input.questionResponses : [],
  };

  QUESTION_ROWS.forEach((rowIdx) => {
    const qKey = ROW_TO_QKEY[rowIdx];
    const rowValue = payload.answersByRow[rowIdx] || payload.answersByRow[String(rowIdx)] || "";
    payload[qKey] = rowValue;
    payload.answersByRow[rowIdx] = rowValue;
  });

  payload.questionResponses.forEach((item) => {
    if (item && item.question) {
      payload.answersByQuestion[item.question] = item.answer || "";
    }
  });

  return payload;
}

async function fetchWithTimeoutAndRetry(url, options = {}) {
  let lastError;

  for (let attempt = 0; attempt <= UPSTREAM_RETRY_COUNT; attempt += 1) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);

    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal,
      });
      clearTimeout(timeout);
      return response;
    } catch (error) {
      clearTimeout(timeout);
      lastError = error;
      if (attempt === UPSTREAM_RETRY_COUNT) break;
    }
  }

  throw lastError;
}

function parseTextResult(rawText) {
  const text = String(rawText || "").trim();

  try {
    return {
      json: JSON.parse(text),
      text,
    };
  } catch {
    const normalized = text.toLowerCase();
    return {
      json: {
        success:
          normalized === "success" ||
          normalized.includes("saved") ||
          normalized.includes("updated"),
        message: text,
      },
      text,
    };
  }
}

function normalizeDraftPayload(input) {
  return {
    savedAt: input.savedAt || new Date().toISOString(),
    answersByRow: { ...(input.answersByRow || {}) },
    answeredCount: Number(input.answeredCount || 0),
    totalQuestions: Number(input.totalQuestions || 0),
    totalScore: Number(input.totalScore || 0),
    totalWeightedScore: Number(input.totalWeightedScore || 0),
    questionResponses: Array.isArray(input.questionResponses) ? input.questionResponses : [],
  };
}

function normalizeSubmissionPayload(input) {
  return {
    submittedAt: input.submittedAt || new Date().toISOString(),
    totalScore: Number(input.totalScore || 0),
    totalWeightedScore: Number(input.totalWeightedScore || 0),
    answersByRow: { ...(input.answersByRow || {}) },
    questionResponses: Array.isArray(input.questionResponses) ? input.questionResponses : [],
    bookingDetails: input.bookingDetails || null,
  };
}

async function ensureSubmissionsTable() {
  if (db.isPostgres) {
    await db.execute(
      `CREATE TABLE IF NOT EXISTS assessment_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        respondent_id INT NOT NULL,
        assessment_type VARCHAR(80) NOT NULL,
        submitted_at TIMESTAMPTZ NULL,
        total_score NUMERIC(12, 2) NOT NULL DEFAULT 0,
        total_weighted_score NUMERIC(12, 2) NOT NULL DEFAULT 0,
        submission_payload TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        status VARCHAR(20) NOT NULL DEFAULT 'Active',
        CONSTRAINT uq_submission_once UNIQUE (respondent_id, assessment_type)
      )`
    );
  } else {
    await db.execute(
      `CREATE TABLE IF NOT EXISTS assessment_submissions (
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        respondent_id INT NOT NULL,
        assessment_type VARCHAR(80) NOT NULL,
        submitted_at DATETIME NULL,
        total_score DECIMAL(12, 2) NOT NULL DEFAULT 0,
        total_weighted_score DECIMAL(12, 2) NOT NULL DEFAULT 0,
        submission_payload LONGTEXT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        status VARCHAR(20) NOT NULL DEFAULT 'Active',
        PRIMARY KEY (id),
        KEY idx_submission_respondent_type (respondent_id, assessment_type),
        KEY idx_submission_created_at (created_at)
      )`
    );

    const [nameCols] = await db.execute(`SHOW COLUMNS FROM assessment_submissions LIKE 'respondent_name'`);
    if (nameCols.length > 0) {
      await db.execute(`ALTER TABLE assessment_submissions DROP COLUMN respondent_name`);
    }

    const [emailCols] = await db.execute(`SHOW COLUMNS FROM assessment_submissions LIKE 'email'`);
    if (emailCols.length > 0) {
      await db.execute(`ALTER TABLE assessment_submissions DROP COLUMN email`);
    }

    const [mobileCols] = await db.execute(`SHOW COLUMNS FROM assessment_submissions LIKE 'mobile'`);
    if (mobileCols.length > 0) {
      await db.execute(`ALTER TABLE assessment_submissions DROP COLUMN mobile`);
    }
  }
}

async function getSubmissionRecordByRespondentId(respondentId) {
  await ensureSubmissionsTable();

  const numId = Number(respondentId);
  if (!Number.isFinite(numId) || numId <= 0) return null;

  const [rows] = await db.execute(
    `SELECT
       s.id,
       s.respondent_id,
       s.submitted_at,
       s.total_score,
       s.total_weighted_score,
       s.submission_payload,
       s.status AS submission_status,
       r.firstname,
       r.lastname,
       r.email,
       r.mobile,
       r.status AS respondent_status
     FROM assessment_submissions s
     JOIN respondent r ON r.id = s.respondent_id AND r.status = 'Active'
     WHERE s.respondent_id = ? AND s.assessment_type = ? AND (s.status IS NULL OR s.status != 'Inactive')
     LIMIT 1`,
    [numId, ASSESSMENT_TYPE]
  );

  if (rows.length === 0) {
    return null;
  }

  const row = rows[0];
  const pii = toDecryptedRespondent(row);
  const fullName = formatFullName(pii.firstname, pii.lastname);

  let parsedPayload = null;
  try {
    parsedPayload = typeof row.submission_payload === "string"
      ? JSON.parse(row.submission_payload)
      : row.submission_payload;
  } catch {
    parsedPayload = null;
  }

  return {
    id: Number(row.id),
    respondentId: Number(row.respondent_id),
    respondent: fullName,
    firstName: String(pii.firstname || "").trim(),
    lastName: String(pii.lastname || "").trim(),
    email: String(pii.email || "").trim().toLowerCase(),
    mobile: String(pii.mobile || "").trim(),
    submittedAt: parsedPayload?.submittedAt || row.submitted_at || null,
    totalScore: Number(parsedPayload?.totalScore ?? row.total_score ?? 0),
    totalWeightedScore: Number(parsedPayload?.totalWeightedScore ?? row.total_weighted_score ?? 0),
    questionResponses: Array.isArray(parsedPayload?.questionResponses) ? parsedPayload.questionResponses : [],
    answersByRow: parsedPayload?.answersByRow || {},
    bookingDetails: parsedPayload?.bookingDetails || null,
  };
}

async function saveSubmissionRecord(respondentId, payload) {
  await ensureSubmissionsTable();

  const numRespondentId = Number(respondentId);
  if (!Number.isFinite(numRespondentId) || numRespondentId <= 0) {
    throw new Error("A valid respondent_id is required to save assessment submission.");
  }

  const [existingRows] = await db.execute(
    `SELECT id, total_score, total_weighted_score, submission_payload
     FROM assessment_submissions
     WHERE respondent_id = ? AND assessment_type = ?
     LIMIT 1`,
    [numRespondentId, ASSESSMENT_TYPE]
  );

  const cleanPayload = normalizeSubmissionPayload(payload);

  if (existingRows.length > 0) {
    const existingRow = existingRows[0];
    let existingPayload = {};
    try {
      existingPayload = typeof existingRow.submission_payload === "string"
        ? JSON.parse(existingRow.submission_payload)
        : existingRow.submission_payload || {};
    } catch (e) {}

    const incomingValidCount = countNonEmptyAnswers(cleanPayload.answersByRow, cleanPayload.questionResponses);

    const mergedAnswersByRow = (incomingValidCount > 0)
      ? cleanPayload.answersByRow
      : (existingPayload.answersByRow || {});

    const mergedQuestionResponses = (incomingValidCount > 0)
      ? cleanPayload.questionResponses
      : (existingPayload.questionResponses || []);

    const mergedTotalScore = Number(cleanPayload.totalScore || 0) > 0
      ? cleanPayload.totalScore
      : Number(existingRow.total_score || existingPayload.totalScore || 0);

    const mergedWeightedScore = Number(cleanPayload.totalWeightedScore || 0) > 0
      ? cleanPayload.totalWeightedScore
      : Number(existingRow.total_weighted_score || existingPayload.totalWeightedScore || 0);

    const mergedBookingDetails = cleanPayload.bookingDetails || existingPayload.bookingDetails || null;

    const mergedPayload = {
      submittedAt: cleanPayload.submittedAt || existingPayload.submittedAt || new Date().toISOString(),
      totalScore: mergedTotalScore,
      totalWeightedScore: mergedWeightedScore,
      answersByRow: mergedAnswersByRow,
      questionResponses: mergedQuestionResponses,
      bookingDetails: mergedBookingDetails,
    };

    await db.execute(
      `UPDATE assessment_submissions
       SET submitted_at = ?,
           total_score = ?,
           total_weighted_score = ?,
           submission_payload = ?,
           status = 'Active'
       WHERE id = ?`,
      [
        mergedPayload.submittedAt,
        mergedTotalScore,
        mergedWeightedScore,
        JSON.stringify(mergedPayload),
        existingRow.id,
      ]
    );
  } else {
    await db.execute(
      `INSERT INTO assessment_submissions
        (respondent_id, assessment_type, submitted_at, total_score, total_weighted_score, submission_payload, status)
       VALUES (?, ?, ?, ?, ?, ?, 'Active')`,
      [
        numRespondentId,
        ASSESSMENT_TYPE,
        cleanPayload.submittedAt,
        cleanPayload.totalScore,
        cleanPayload.totalWeightedScore,
        JSON.stringify(cleanPayload),
      ]
    );
  }
}

async function findExistingAssessmentSubmission({ respondentId, email }) {
  await ensureSubmissionsTable();

  let targetRespondentId = Number(respondentId);

  if ((!Number.isFinite(targetRespondentId) || targetRespondentId <= 0) && email) {
    const canonical = await getByEmail(email);
    if (canonical) {
      targetRespondentId = canonical.id;
    }
  }

  if (Number.isFinite(targetRespondentId) && targetRespondentId > 0) {
    const [rows] = await db.execute(
      `SELECT
         s.id,
         s.respondent_id,
         s.submitted_at,
         s.total_score,
         s.total_weighted_score,
         s.submission_payload,
         s.created_at,
         r.firstname,
         r.lastname,
         r.email,
         r.mobile,
         r.status AS respondent_status
       FROM assessment_submissions s
       JOIN respondent r ON r.id = s.respondent_id AND r.status = 'Active'
       WHERE s.respondent_id = ? AND s.assessment_type = ? AND (s.status IS NULL OR s.status != 'Inactive')
       LIMIT 1`,
      [targetRespondentId, ASSESSMENT_TYPE]
    );

    if (rows.length > 0) {
      const row = rows[0];
      const pii = toDecryptedRespondent(row);
      return {
        ...row,
        respondent_name: formatFullName(pii.firstname, pii.lastname),
        email: String(pii.email || "").trim().toLowerCase(),
      };
    }
  }

  return null;
}

const DEFAULT_QUESTIONS_LIST = [
  { rowIndex: 6, number: 1, question: "When your team discusses a decision, who typically speaks first?", weight: 2 },
  { rowIndex: 7, number: 2, question: "Think of a recent decision where something important emerged after the fact. What do you think stopped it surfacing in the room?", weight: 2 },
  { rowIndex: 8, number: 3, question: "How would you describe the pace of decisions in your leadership meetings?", weight: 1 },
  { rowIndex: 9, number: 4, question: "Are there people in your team you know have strong views but rarely voice them in meetings?", weight: 2 },
  { rowIndex: 12, number: 5, question: "Who challenges in your leadership meetings?", weight: 2 },
  { rowIndex: 13, number: 6, question: "When someone does push back in a discussion, how does the room typically respond?", weight: 2 },
  { rowIndex: 14, number: 7, question: "Are there topics in your leadership discussions that feel quietly off-limits — where challenge just doesn't happen?", weight: 1 },
  { rowIndex: 15, number: 8, question: "After meetings, do you hear different views from people in the corridor to what was said in the room?", weight: 2 },
  { rowIndex: 18, number: 9, question: "When you signal your own view early in a discussion, what tends to happen?", weight: 3 },
  { rowIndex: 19, number: 10, question: "Do you feel you hear from the people with the most relevant knowledge, or those most comfortable speaking?", weight: 3 },
  { rowIndex: 20, number: 11, question: "When a discussion goes in circles, what is your instinct?", weight: 2 },
  { rowIndex: 21, number: 12, question: "If you could change one thing about how your team makes complex decisions, what would it be?", weight: 1 },
];

function extractAnswerFromRowMap(byRow, q, idx) {
  if (!byRow || typeof byRow !== "object") return "";

  const qNum = q.number || (idx + 1);
  const rIdx = q.rowIndex;

  const candidateKeys = [
    rIdx, String(rIdx),
    idx, String(idx),
    qNum, String(qNum),
    `q${qNum}`, `q${idx + 1}`, `Q${qNum}`,
    `row${rIdx}`, `row_${rIdx}`,
  ];

  for (const key of candidateKeys) {
    const val = byRow[key];
    if (val !== undefined && val !== null && String(val).trim() !== "" && String(val).trim() !== "-") {
      return String(val).trim();
    }
  }

  return "";
}

function buildCompleteQuestionResponses(existingQuestionResponses, answersByRow) {
  const byRow = answersByRow && typeof answersByRow === "object" ? answersByRow : {};
  const existingMap = new Map();

  if (Array.isArray(existingQuestionResponses)) {
    existingQuestionResponses.forEach((item, idx) => {
      if (item && (item.question || item.number || item.rowIndex)) {
        const key = item.rowIndex || item.number || (idx + 1);
        existingMap.set(String(key), item);
      }
    });
  }

  return DEFAULT_QUESTIONS_LIST.map((q, idx) => {
    const existingItem = existingMap.get(String(q.rowIndex)) || existingMap.get(String(q.number));
    const extractedAns = extractAnswerFromRowMap(byRow, q, idx);
    const finalAnswer = (existingItem && String(existingItem.answer || "").trim() && String(existingItem.answer).trim() !== "-")
      ? String(existingItem.answer).trim()
      : extractedAns;

    return {
      rowIndex: q.rowIndex,
      number: q.number,
      question: q.question,
      answer: finalAnswer || "—",
      score: existingItem?.score ?? null,
      weight: existingItem?.weight ?? q.weight,
      weightedScore: existingItem?.weightedScore ?? null,
    };
  });
}

function normalizeSubmissionRow(row) {
  const pii = toDecryptedRespondent(row);
  const fullName = formatFullName(pii.firstname, pii.lastname);
  const email = String(pii.email || "").trim().toLowerCase();
  const mobile = String(pii.mobile || "").trim();

  const payload = typeof row.submission_payload === "string"
    ? JSON.parse(row.submission_payload || "{}")
    : row.submission_payload || {};

  const submittedAt = payload.submittedAt || row.submitted_at || null;
  const timestamp = submittedAt || row.created_at || null;
  const fullQuestions = buildCompleteQuestionResponses(payload.questionResponses, payload.answersByRow);

  return {
    id: Number(row.id),
    respondentId: Number(row.respondent_id),
    source: "internal",
    respondent: fullName,
    firstName: String(pii.firstname || "").trim(),
    lastName: String(pii.lastname || "").trim(),
    email,
    mobile,
    submittedAt,
    timestamp,
    totalScore: Number(payload.totalScore ?? row.total_score ?? 0),
    totalWeightedScore: Number(payload.totalWeightedScore ?? row.total_weighted_score ?? 0),
    questionResponses: fullQuestions,
    questions: fullQuestions,
    answersByRow: payload.answersByRow || {},
    createdAt: row.created_at,
    status: row.submission_status || "Active",
    respondentStatus: row.respondent_status || "Active",
  };
}

function countNonEmptyAnswers(answersByRow, questionResponses) {
  let count = 0;
  if (Array.isArray(questionResponses)) {
    count += questionResponses.filter((q) => q && String(q.answer || "").trim() !== "" && String(q.answer).trim() !== "—" && String(q.answer).trim() !== "-").length;
  }
  if (count > 0) return count;

  if (answersByRow && typeof answersByRow === "object") {
    Object.values(answersByRow).forEach((v) => {
      if (v !== undefined && v !== null && String(v).trim() !== "" && String(v).trim() !== "—" && String(v).trim() !== "-") {
        count += 1;
      }
    });
  }
  return count;
}

async function fetchSubmissionsFromDatabase() {
  await ensureSubmissionsTable();

  const [rows] = await db.execute(
    `SELECT
       s.id,
       s.respondent_id,
       s.assessment_type,
       s.status AS submission_status,
       s.submitted_at,
       s.total_score,
       s.total_weighted_score,
       s.submission_payload,
       s.created_at,
       r.firstname,
       r.lastname,
       r.email,
       r.mobile,
       r.status AS respondent_status
     FROM assessment_submissions s
     JOIN respondent r ON r.id = s.respondent_id
     WHERE (r.status IS NULL OR UPPER(r.status) != 'INACTIVE')
       AND (s.status IS NULL OR UPPER(s.status) != 'INACTIVE')
     ORDER BY s.submitted_at DESC, s.id DESC`
  );

  return rows.map((r) => normalizeSubmissionRow(r));
}

async function deleteSubmissionById(id) {
  await ensureSubmissionsTable();

  const [subRows] = await db.execute(
    `SELECT respondent_id FROM assessment_submissions WHERE id = ?`,
    [id]
  );

  const [result] = await db.execute(
    `UPDATE assessment_submissions SET status = 'Inactive' WHERE id = ?`,
    [id]
  );

  if (subRows.length > 0 && subRows[0].respondent_id) {
    await db.execute(`UPDATE respondent SET status = 'Inactive' WHERE id = ?`, [subRows[0].respondent_id]);
  }

  return { deleted: Number(result?.affectedRows || 0) > 0 };
}

async function reactivateSubmissionById(id) {
  await ensureSubmissionsTable();

  const [subRows] = await db.execute(
    `SELECT respondent_id FROM assessment_submissions WHERE id = ?`,
    [id]
  );

  const [result] = await db.execute(
    `UPDATE assessment_submissions SET status = 'Active' WHERE id = ?`,
    [id]
  );

  if (subRows.length > 0 && subRows[0].respondent_id) {
    await db.execute(`UPDATE respondent SET status = 'Active' WHERE id = ?`, [subRows[0].respondent_id]);
  }

  return { reactivated: Number(result?.affectedRows || 0) > 0 };
}

exports.saveDraft = async (req, res) => {
  try {
    const respondentId = req.user?.id;
    if (!respondentId) {
      return res.status(401).json({ success: false, message: "Authentication required to save draft." });
    }

    const canonicalRespondent = await getActiveById(respondentId);
    if (!canonicalRespondent) {
      return res.status(403).json({ success: false, message: "Active respondent account required." });
    }

    const payload = normalizeDraftPayload(req.body || {});

    if (Object.keys(payload.answersByRow).length === 0) {
      return res.status(400).json({ success: false, message: "At least one answer is required to save a draft." });
    }

    if (db.isPostgres) {
      await db.execute(
        `INSERT INTO assessment_drafts
          (respondent_id, assessment_type, answered_count, draft_payload, updated_at)
         VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
         ON CONFLICT (respondent_id, assessment_type)
         DO UPDATE SET
          answered_count = EXCLUDED.answered_count,
          draft_payload = EXCLUDED.draft_payload,
          updated_at = CURRENT_TIMESTAMP`,
        [
          respondentId,
          ASSESSMENT_TYPE,
          payload.answeredCount,
          JSON.stringify(payload),
        ]
      );
    } else {
      await db.execute(
        `INSERT INTO assessment_drafts
          (respondent_id, assessment_type, answered_count, draft_payload)
         VALUES (?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE
          answered_count = VALUES(answered_count),
          draft_payload = VALUES(draft_payload),
          updated_at = CURRENT_TIMESTAMP`,
        [
          respondentId,
          ASSESSMENT_TYPE,
          payload.answeredCount,
          JSON.stringify(payload),
        ]
      );
    }

    return res.json({
      success: true,
      message: `Draft saved. You answered ${payload.answeredCount} questions.`,
      data: {
        ...payload,
        respondentId,
        respondent: canonicalRespondent.fullName,
      },
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to save draft",
      details: error.message,
    });
  }
};

exports.savePublicDraft = async (req, res) => {
  try {
    const respondentId = Number(req.body?.respondentId || 0);

    if (!Number.isFinite(respondentId) || respondentId <= 0) {
      return res.status(400).json({ success: false, message: "Valid respondentId is required." });
    }

    const canonicalRespondent = await getActiveById(respondentId);
    if (!canonicalRespondent) {
      return res.status(404).json({ success: false, message: "Active respondent not found for given respondentId." });
    }

    const payload = normalizeDraftPayload(req.body || {});

    if (db.isPostgres) {
      await db.execute(
        `INSERT INTO assessment_drafts
          (respondent_id, assessment_type, answered_count, draft_payload, updated_at)
         VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
         ON CONFLICT (respondent_id, assessment_type)
         DO UPDATE SET
          answered_count = EXCLUDED.answered_count,
          draft_payload = EXCLUDED.draft_payload,
          updated_at = CURRENT_TIMESTAMP`,
        [
          respondentId,
          ASSESSMENT_TYPE,
          payload.answeredCount,
          JSON.stringify(payload),
        ]
      );
    } else {
      await db.execute(
        `INSERT INTO assessment_drafts
          (respondent_id, assessment_type, answered_count, draft_payload)
         VALUES (?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE
          answered_count = VALUES(answered_count),
          draft_payload = VALUES(draft_payload),
          updated_at = CURRENT_TIMESTAMP`,
        [
          respondentId,
          ASSESSMENT_TYPE,
          payload.answeredCount,
          JSON.stringify(payload),
        ]
      );
    }

    return res.json({
      success: true,
      message: `Draft saved. You answered ${payload.answeredCount} questions.`,
      data: {
        ...payload,
        respondentId,
        respondent: canonicalRespondent.fullName,
      },
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to save public draft",
      details: error.message,
    });
  }
};

exports.getDraft = async (req, res) => {
  try {
    const respondentId = req.user?.id;
    if (!respondentId) {
      return res.status(401).json({ success: false, message: "Authentication required to load draft." });
    }

    const [rows] = await db.execute(
      `SELECT
         d.id,
         d.respondent_id,
         d.answered_count,
         d.draft_payload,
         d.updated_at,
         r.firstname,
         r.lastname,
         r.email,
         r.mobile,
         r.status
       FROM assessment_drafts d
       JOIN respondent r ON r.id = d.respondent_id AND r.status = 'Active'
       WHERE d.respondent_id = ? AND d.assessment_type = ?`,
      [respondentId, ASSESSMENT_TYPE]
    );

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: "No draft found." });
    }

    const row = rows[0];
    const pii = toDecryptedRespondent(row);
    const fullName = formatFullName(pii.firstname, pii.lastname);

    const payload = typeof row.draft_payload === "string"
      ? JSON.parse(row.draft_payload)
      : row.draft_payload;

    return res.json({
      success: true,
      data: {
        ...payload,
        respondentId: Number(row.respondent_id),
        respondent: fullName,
        email: String(pii.email || "").trim().toLowerCase(),
        mobile: String(pii.mobile || "").trim(),
        answeredCount: Number(payload.answeredCount || row.answered_count || 0),
        savedAt: payload.savedAt || row.updated_at,
      },
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to load draft",
      details: error.message,
    });
  }
};

exports.getPublicDraft = async (req, res) => {
  try {
    const respondentId = Number(req.params.respondentId || 0);

    if (!Number.isFinite(respondentId) || respondentId <= 0) {
      return res.status(400).json({ success: false, message: "Valid respondentId is required." });
    }

    const [rows] = await db.execute(
      `SELECT
         d.id,
         d.respondent_id,
         d.answered_count,
         d.draft_payload,
         d.updated_at,
         r.firstname,
         r.lastname,
         r.email,
         r.mobile,
         r.status
       FROM assessment_drafts d
       JOIN respondent r ON r.id = d.respondent_id AND r.status = 'Active'
       WHERE d.respondent_id = ? AND d.assessment_type = ?`,
      [respondentId, ASSESSMENT_TYPE]
    );

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: "No draft found." });
    }

    const row = rows[0];
    const pii = toDecryptedRespondent(row);
    const fullName = formatFullName(pii.firstname, pii.lastname);

    const payload = typeof row.draft_payload === "string"
      ? JSON.parse(row.draft_payload)
      : row.draft_payload;

    return res.json({
      success: true,
      data: {
        ...payload,
        respondentId: Number(row.respondent_id),
        respondent: fullName,
        email: String(pii.email || "").trim().toLowerCase(),
        mobile: String(pii.mobile || "").trim(),
        answeredCount: Number(payload.answeredCount || row.answered_count || 0),
        savedAt: payload.savedAt || row.updated_at,
      },
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ success: false, message: "Failed to load public draft", details: error.message });
  }
};

exports.deletePublicDraft = async (req, res) => {
  try {
    const respondentId = Number(req.params.respondentId || 0);
    if (!Number.isFinite(respondentId) || respondentId <= 0) {
      return res.status(400).json({ success: false, message: "Valid respondentId is required." });
    }

    const [result] = await db.execute(
      `DELETE FROM assessment_drafts
       WHERE respondent_id = ? AND assessment_type = ?`,
      [respondentId, ASSESSMENT_TYPE]
    );

    return res.json({
      success: true,
      message: result.affectedRows > 0 ? "Draft cleared." : "No draft found to clear.",
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to clear draft",
      details: error.message,
    });
  }
};

exports.deleteDraft = async (req, res) => {
  try {
    const respondentId = req.user?.id;
    if (!respondentId) {
      return res.status(401).json({ success: false, message: "Authentication required to delete draft." });
    }

    const [result] = await db.execute(
      `DELETE FROM assessment_drafts
       WHERE respondent_id = ? AND assessment_type = ?`,
      [respondentId, ASSESSMENT_TYPE]
    );

    return res.json({
      success: true,
      message: result.affectedRows > 0 ? "Draft cleared." : "No draft found to clear.",
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to clear draft",
      details: error.message,
    });
  }
};

exports.submitAssessment = async (req, res) => {
  try {
    const incomingRespondentId = Number(req.user?.id || req.body?.respondentId || 0);
    const incomingEmail = String(req.body?.email || "").trim().toLowerCase();

    let canonicalRespondent = null;

    if (incomingRespondentId > 0) {
      canonicalRespondent = await getActiveById(incomingRespondentId);
    }

    if (!canonicalRespondent && incomingEmail) {
      canonicalRespondent = await getByEmail(incomingEmail, { activeOnly: true });
    }

    if (!canonicalRespondent) {
      return res.status(400).json({
        success: false,
        message: "Unable to submit: Active respondent record not found. Please register or enter valid details.",
      });
    }

    const normalizedPayload = normalizeSubmissionPayload(req.body || {});
    const respondentId = canonicalRespondent.id;

    const existingSubmission = await findExistingAssessmentSubmission({
      respondentId,
      email: canonicalRespondent.email,
    });

    const incomingValidCount = countNonEmptyAnswers(normalizedPayload.answersByRow, normalizedPayload.questionResponses);
    const isReschedule = Boolean(req.body?.isReschedule || req.body?.bookingDetails?.isReschedule) || (Boolean(existingSubmission) && incomingValidCount === 0);

    const { isSlotBookedOrBlocked } = require("../utils/slotService");
    const booking = normalizedPayload.bookingDetails || {};
    if (booking.scheduledDate && booking.scheduledTime) {
      const isUnavailable = await isSlotBookedOrBlocked(booking.scheduledDate, booking.scheduledTime);
      if (isUnavailable) {
        return res.status(409).json({
          success: false,
          message: `The time slot ${booking.scheduledTime} on ${booking.scheduledDate} was just booked by another user or is unavailable. Please choose another time slot.`,
        });
      }
    }

    const scriptUrl = process.env.GOOGLE_SCRIPT_URL || DEFAULT_SCRIPT_URL;
    const outgoingPayload = buildScriptPayload(normalizedPayload, canonicalRespondent);

    let acceptedByUpstream = false;
    let parsed = null;
    let rawText = null;

    if (!isReschedule) {
      try {
        const upstream = await fetchWithTimeoutAndRetry(scriptUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(outgoingPayload),
        });

        rawText = await upstream.text();
        parsed = parseTextResult(rawText);

        const normalizedText = String(parsed.text || "").trim().toLowerCase();
        acceptedByUpstream =
          parsed?.json?.success === true ||
          normalizedText === "success" ||
          normalizedText.includes("saved") ||
          normalizedText.includes("updated");
      } catch (upstreamError) {
        console.error("Failed to submit to Google Script upstream:", upstreamError.message || upstreamError);
        rawText = upstreamError.message || String(upstreamError);
        parsed = { json: { success: false, message: rawText }, text: rawText };
      }
    } else {
      acceptedByUpstream = true;
      parsed = { json: { success: true, message: "Skipped duplicate Google Sheet append on reschedule." }, text: "success" };
    }

    try {
      await saveSubmissionRecord(respondentId, normalizedPayload);
    } catch (dbError) {
      console.error("Failed to save assessment submission to database:", dbError.message || dbError);
      return res.status(500).json({
        success: false,
        dbSaved: false,
        sheetSuccess: acceptedByUpstream,
        message: "Failed to save assessment submission to the database.",
        details: dbError.message,
      });
    }

    let mailSent = false;
    let adminMailSent = false;

    try {
      const recipient = canonicalRespondent.email;
      if (recipient) {
        mailSent = await sendAssessmentResultEmail(recipient, {
          respondent: canonicalRespondent.fullName,
          firstName: canonicalRespondent.firstname,
          lastName: canonicalRespondent.lastname,
          email: canonicalRespondent.email,
          totalScore: normalizedPayload.totalScore,
          totalWeightedScore: normalizedPayload.totalWeightedScore,
          submittedAt: normalizedPayload.submittedAt,
          answersByRow: normalizedPayload.answersByRow,
          questionResponses: normalizedPayload.questionResponses,
          bookingDetails: normalizedPayload.bookingDetails,
        });
      }
      try {
        adminMailSent = await sendAdminNotificationEmail({
          respondent: canonicalRespondent.fullName,
          firstName: canonicalRespondent.firstname,
          lastName: canonicalRespondent.lastname,
          email: canonicalRespondent.email,
          totalScore: normalizedPayload.totalScore,
          totalWeightedScore: normalizedPayload.totalWeightedScore,
          submittedAt: normalizedPayload.submittedAt,
          answersByRow: normalizedPayload.answersByRow,
          questionResponses: normalizedPayload.questionResponses,
          bookingDetails: normalizedPayload.bookingDetails,
        });
      } catch (err) {
        console.error("Failed to send admin notification:", err.message);
      }
    } catch (e) {
      mailSent = false;
      adminMailSent = false;
      console.error("Failed to send assessment email:", e?.message);
    }

    // Remove draft after submission
    try {
      await db.execute(
        `DELETE FROM assessment_drafts WHERE respondent_id = ? AND assessment_type = ?`,
        [respondentId, ASSESSMENT_TYPE]
      );
    } catch (e) {
      console.error("Failed to remove draft after submission:", e.message);
    }

    let scoringResult = null;
    try {
      const s = computeTab3Scoring(normalizedPayload.questionResponses);
      scoringResult = {
        zone: s.zone,
        zoneSummary: s.zoneSummary,
        overallPct: s.overallPctDisplay,
        rawTotal: s.rawTotal,
        weakestCategory: s.weakestCategory,
        action: s.actions.onScreen,
      };
    } catch (e) {
      console.error("Scoring computation for response payload failed:", e?.message);
    }

    const responsePayload = {
      success: acceptedByUpstream,
      dbSaved: true,
      sheetSuccess: acceptedByUpstream,
      mailSent,
      scoring: scoringResult,
      message: acceptedByUpstream
        ? (parsed?.json?.message || rawText || "Assessment submitted successfully.")
        : (parsed?.json?.message || rawText || "Saved to DB but failed to submit to Google Sheet."),
      respondent: {
        id: canonicalRespondent.id,
        firstName: canonicalRespondent.firstname,
        lastName: canonicalRespondent.lastname,
        email: canonicalRespondent.email,
        mobile: canonicalRespondent.mobile,
        status: canonicalRespondent.status,
      },
    };
    return res.status(200).json(responsePayload);
  } catch (error) {
    console.error(error);
    return res.status(502).json({
      success: false,
      message: "Failed to submit data to Google Sheet endpoint",
      details: error.message,
    });
  }
};

exports.getSubmissionStatus = async (req, res) => {
  try {
    const respondentId = Number(req.user?.id || 0);
    if (!respondentId) {
      return res.status(400).json({ success: false, message: "Authenticated user required to check submission status." });
    }

    const submission = await getSubmissionRecordByRespondentId(respondentId);

    if (!submission) {
      return res.json({ success: true, submitted: false });
    }

    return res.json({
      success: true,
      submitted: true,
      data: submission,
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to fetch submission status",
      details: error.message,
    });
  }
};

exports.getSubmissions = async (_req, res) => {
  try {
    const submissions = await fetchSubmissionsFromDatabase();

    return res.status(200).json({
      success: true,
      submissions,
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to load submissions from the database.",
      details: error.message,
    });
  }
};

exports.deleteSubmission = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id) || id <= 0) {
      return res.status(400).json({ success: false, message: "Invalid submission id." });
    }

    const result = await deleteSubmissionById(id);
    if (!result.deleted) {
      return res.status(404).json({ success: false, message: "Submission not found." });
    }

    return res.json({
      success: true,
      message: "Submission marked as inactive.",
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to update submission status.",
      details: error.message,
    });
  }
};

exports.reactivateSubmission = async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id) || id <= 0) {
      return res.status(400).json({ success: false, message: "Invalid submission id." });
    }

    const result = await reactivateSubmissionById(id);
    if (!result.reactivated) {
      return res.status(404).json({ success: false, message: "Submission not found." });
    }

    return res.json({
      success: true,
      message: "Submission reactivated.",
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      success: false,
      message: "Failed to reactivate submission.",
      details: error.message,
    });
  }
};

exports.cancelBooking = async (req, res) => {
  try {
    const email = String(req.body?.email || "").trim().toLowerCase();
    if (!email) {
      return res.status(400).json({ success: false, message: "Email is required to cancel an appointment." });
    }

    const canonicalRespondent = await getByEmail(email);
    if (!canonicalRespondent) {
      return res.status(404).json({ success: false, message: "No respondent found for this email address." });
    }

    const [rows] = await db.execute(
      `SELECT id, submission_payload FROM assessment_submissions WHERE respondent_id = ? ORDER BY id DESC LIMIT 1`,
      [canonicalRespondent.id]
    );

    if (rows.length === 0) {
      return res.status(404).json({ success: false, message: "No active submission/booking found for this respondent." });
    }

    const row = rows[0];
    let payload = {};
    try {
      payload = typeof row.submission_payload === "string" ? JSON.parse(row.submission_payload) : row.submission_payload || {};
    } catch (e) {}

    const booking = payload.bookingDetails || {};
    const scheduledDate = booking.scheduledDate || "";
    const scheduledTime = booking.scheduledTime || "";
    const timeZone = booking.timeZone || "India,Asia/Kolkata";

    const updatedBookingDetails = {
      ...booking,
      isCancelled: true,
      status: "cancelled",
      cancelledAt: new Date().toISOString(),
    };

    const updatedPayload = {
      ...payload,
      isCancelled: true,
      bookingDetails: updatedBookingDetails,
    };

    await db.execute(
      `UPDATE assessment_submissions SET submission_payload = ? WHERE id = ?`,
      [JSON.stringify(updatedPayload), row.id]
    );

    const mailPayload = {
      firstName: canonicalRespondent.firstname || "Participant",
      lastName: canonicalRespondent.lastname || "",
      respondent: canonicalRespondent.fullName || "Participant",
      email: canonicalRespondent.email,
      scheduledDate,
      scheduledTime,
      timeZone,
    };

    const { sendCancellationUserEmail, sendCancellationAdminEmail } = require("../utils/mailer");
    let userMailSent = false;
    let adminMailSent = false;

    try {
      userMailSent = await sendCancellationUserEmail(canonicalRespondent.email, mailPayload);
    } catch (e) {
      console.error("Failed to send cancellation user email:", e);
    }

    try {
      adminMailSent = await sendCancellationAdminEmail(mailPayload);
    } catch (e) {
      console.error("Failed to send cancellation admin email:", e);
    }

    return res.json({
      success: true,
      message: "Appointment cancelled successfully. The time slot is now released back to available slots.",
      userMailSent,
      adminMailSent,
      data: {
        scheduledDate,
        scheduledTime,
        email: canonicalRespondent.email,
      },
    });
  } catch (error) {
    console.error("Error cancelling booking:", error);
    return res.status(500).json({ success: false, message: "Internal server error while cancelling appointment.", details: error.message });
  }
};
